# Generated by Django 3.2 on 2022-12-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing_Board',
            fields=[
                ('Board_id', models.AutoField(primary_key=True, serialize=False)),
                ('Board_share', models.CharField(choices=[('한다', 'yes'), ('안한다', 'no')], default='', max_length=100)),
                ('Board_gtype', models.CharField(choices=[('그립톡', 'griptok'), ('머그컵', 'mugcub'), ('키링', 'keyring'), ('티셔츠', 'tshirt'), ('핸드폰 케이스', 'phonecase')], default='', max_length=100)),
                ('Board_image', models.FileField(upload_to='img')),
                ('Board_title', models.CharField(max_length=250, verbose_name='제목')),
                ('Board_content', models.TextField(verbose_name='내용')),
                ('Board_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
