# Generated by Django 3.2 on 2022-12-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Board_id', models.AutoField(primary_key=True, serialize=False)),
                ('Board_share', models.CharField(choices=[('Yes', '한다'), ('no', '안한다')], default='', max_length=100, verbose_name='공구 여부')),
                ('Board_gtype', models.CharField(max_length=100)),
                ('Board_image', models.FileField(upload_to='C:\\existing_repo\\BP\x07rticle\\image')),
                ('Board_title', models.CharField(max_length=250, verbose_name='제목')),
                ('Board_content', models.TextField(default='내용을 입력하세요')),
                ('Board_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sharing_Board',
        ),
    ]
