# Generated by Django 3.2 on 2022-12-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20221209_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Board_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_image',
            field=models.ImageField(upload_to='C:\\existing_repo\\BP\x07rticle\\image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_share',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_title',
            field=models.CharField(max_length=250),
        ),
    ]
