# Generated by Django 3.2 on 2022-12-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20221209_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Board_content',
            field=models.TextField(default='내용을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_image',
            field=models.FileField(upload_to='C:\\existing_repo\\BP\x07rticle\\image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_share',
            field=models.CharField(choices=[('Yes', '한다'), ('no', '안한다')], default='', max_length=100, verbose_name='공구 여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_title',
            field=models.CharField(max_length=250, verbose_name='제목'),
        ),
    ]
