# Generated by Django 3.2 on 2022-12-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20221209_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Board_image',
            field=models.ImageField(upload_to='C:\\existing_repo\\BP\x07rticle\\image'),
        ),
    ]
