# Generated by Django 3.2 on 2022-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_post_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Board_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_share',
            field=models.CharField(choices=[('Yes', '한다'), ('no', '안한다')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_title',
            field=models.CharField(max_length=250),
        ),
    ]
