# Generated by Django 3.2 on 2022-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20221209_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Board_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
