# Generated by Django 3.2 on 2022-12-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_post_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Board_image',
            field=models.ImageField(upload_to='article/image/'),
        ),
    ]
