# Generated by Django 3.2 on 2022-12-13 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20221210_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Board_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='Board_gtype',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Post_Image',
            fields=[
                ('Image_id', models.AutoField(primary_key=True, serialize=False)),
                ('Board_image', models.ImageField(upload_to='article/image/')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.post')),
            ],
        ),
    ]
