# Generated by Django 3.2 on 2022-12-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20221213_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_image',
            old_name='Post',
            new_name='Post_id',
        ),
    ]
