# Generated by Django 3.2 on 2022-12-13 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_rename_post_post_image_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_id', models.IntegerField(default=0)),
                ('Board_image', models.ImageField(upload_to='article/image/')),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Post_Image',
        ),
    ]
