# Generated by Django 3.2 on 2022-12-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20221213_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='Post_id',
            new_name='Post',
        ),
    ]
