# Generated by Django 3.2 on 2022-12-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='Image_id',
        ),
    ]
